###########
# BUILDER #
###########

FROM python:3.12-slim as builder

RUN pip install pdm

ENV POETRY_NO_INTERACTION=1 \
    POETRY_VIRTUALENVS_IN_PROJECT=1 \
    POETRY_VIRTUALENVS_CREATE=1 \
    POETRY_CACHE_DIR=/tmp/poetry_cache

WORKDIR /src

COPY pyproject.toml poetry.lock ./

RUN pdm install

#########
# FINAL #
#########

FROM python:3.12-slim as final

RUN apt-get update && apt-get install -y curl

ENV VIRTUAL_ENV=/src/.venv \
    PATH="/src/.venv/bin:$PATH" \
    PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1

COPY --from=builder ${VIRTUAL_ENV} ${VIRTUAL_ENV}

ENV PYTHONPATH="${PYTHONPATH}:/src"

COPY ./ ./src

WORKDIR /src

COPY entrypoint.sh /src/entrypoint.sh

RUN chmod +x /src/entrypoint.sh

ENTRYPOINT ["/src/entrypoint.sh"]