version: '3'
services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ../..:/workspaces:cached
    command: sleep infinity
    depends_on:
      - postgres
    networks:
      - zypl

  postgres:
    image: postgres
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: zypl
    volumes:
      - ../data/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - zypl

  adminer_container:
    image: adminer:latest
    environment:
      ADMINER_DEFAULT_SERVER: postgres
    ports:
      - 8080:8080
    networks:
      - zypl

networks:
  zypl:
    driver: bridge
